# Generated by Django 3.0.5 on 2026-07-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20260710_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='question_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
