# Generated by Django 3.0.5 on 2026-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20260714_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pic/Student/'),
        ),
    ]
